#!/usr/bin/env python3
"""
sacrebleu test fixture

Do not rely on sacrebleu in tests. This mocks sacrebleu by accepting all of the input,
and then finally outputting fake scores. The arguments are saved to sacrebleu.args.txt
"""

import json
import os
import sys

artifacts_dir = os.environ.get("TEST_ARTIFACTS")

if not artifacts_dir:
    raise Exception("TEST_ARTIFACTS was not set.")

if not os.path.exists(artifacts_dir):
    raise Exception("The TEST_ARTIFACTS directory did not exist")

# Write the arguments to file
arguments = sys.argv[1:]
with open(os.path.join(artifacts_dir, "sacrebleu.args.txt"), "w") as file:
    json.dump(arguments, file)

with open(os.path.join(artifacts_dir, "sacrebleu.stdin.txt"), "w") as file:
    file.write(sys.stdin.read())

# Output fake scores.
print("12.3\n45.6")
